development:
  adapter: postgresql
  encoding: unicode
  database: coucheboard_development
  pool: 5
  username: ubuntu
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: coucheboard_test
  pool: 5
  username: ubuntu
  password: